### ISSUE TITLE
Fehlende Dependencies auf Maven Repo

### ISSUE THREAD

**Issue by LukasJo96** [gomint/gomint#1]
Hallo,

ich wollte das Projekt soeben importieren, allerdings fehlen auf den beiden Maven Repos folgende Dependencies:

io.gomint.taglib v. 0.2.1

io.gomint.jraknet v 1.3.4

**Comment by geNAZt** [comment]
Ok zuerst sollten alle Issues auf englisch erstellt werden. Zur Issue selbst: Das repo ist online und ich kann alle Dependencies resolven und herunter laden
