### ISSUE TITLE
You can place a block at the place you're standing

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#110]
1.

![image](https://user-images.githubusercontent.com/19636759/36356612-abb9e4ea-14f4-11e8-82a8-e437bc49fa3e.png)

2.
![image](https://user-images.githubusercontent.com/19636759/36356614-b4a5ab5c-14f4-11e8-9848-60dad2cf2bf3.png)

**Comment by Janmm14** [comment]
also possible to place blocks where others are standing?
