### ISSUE TITLE
logger formatting not working

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#120]
Example: The code
```java
getLogger().info("To gain OP enter /opmintsetup %s", controller.getConfig().getConfigSecret());
```
outputs this into the console
```
To gain OP enter /opmintsetup %s
```

**Comment by geNAZt** [comment]
Logger format placeholders are {}. Those are defined by slf4j and are called format anchors. "Normal" Java way format patterns will not work in logger statements
