### ISSUE TITLE
Need event.getPlacedBlock() in BlockPlaceEvent 

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#145]

**Comment by Janmm14** [comment]
I'd say: getBlockToPlace()

**Comment by LucGamesYT** [comment]
Diese Methode gibt es nicht

**Comment by Janmm14** [comment]
Ich wollte einen alternativen Namen für die einzufügende Methode vorschlagen.

**Comment by LucGamesYT** [comment]
Ach so, ja beim BlockBreakEvent heißt die Methode auch so in etwa
