### ISSUE TITLE
Entities are not loading

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#167]

**Comment by ghost** [comment]
Can you please provide any further description?

**Comment by Goodstuff4UonYT** [comment]
@Shad0wCore GoMint is not loading saved entities from the world.. (Only Villager)

**Comment by enricoangelon** [comment]
you mean entities saved on level.dat?

**Comment by Janmm14** [comment]
Entities are not saved in level.dat, but inside the region files.
