### ISSUE TITLE
TargetValidator does not support spaces in names

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#171]
TargetValidator does not support spaces in names

**Comment by geNAZt** [comment]
Problem about spaces in TargetValidator is that a name could have up too endless spaces, so i don't know how much text i should consume (thats the reason text/string validator only works at the end of a command). Supporting this would need a proper Canidate evalution system for commands.

**Comment by Janmm14** [comment]
Get everything at start and reduce until you found name.

Edit: Or require "" for names with spaces.

**Comment by Goodstuff4UonYT** [comment]
To put it in quotation marks is the right way, I think
