### ISSUE TITLE
removeItem method is missing

### ISSUE THREAD

**Issue by EinBexiii** [gomint/gomint#176]
EntityPlayer.removeItem(Itemstack itemstack, int amount);
EntityPlayer.removeItem(String itemname, int amount);
...

**Comment by Janmm14** [comment]
Ich würde niemals die Methode mit dem String einbauen.
Vielleicht lieber eine Methode, welches ein Predicate<ItemStack> bekommt, welches sagt, ob das Item dazugehört oder nicht.
