### ISSUE TITLE
Items are not swimming in/with water

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#183]

**Comment by Janmm14** [comment]
Are they doing this in singleplayer? WTF

**Comment by Goodstuff4UonYT** [comment]
Das die halt den Berg herunter mit dem Wasser schwimmen meine ich. xD @Janmm14

**Comment by Goodstuff4UonYT** [comment]
![image](https://user-images.githubusercontent.com/19636759/38164163-4cb30518-3500-11e8-852c-c605085a5ac6.png)

**Comment by Janmm14** [comment]
Achsoo

**Comment by Goodstuff4UonYT** [comment]
https://cdn.discordapp.com/attachments/409690380205031425/459989480934473728/image.jpg
