### ISSUE TITLE
TargetValidator are broken

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#190]
TargetValidator are broken:

- https://cdn.discordapp.com/attachments/433289132710690819/433289156932665345/unknown.png
- https://cdn.discordapp.com/attachments/433289132710690819/433289214147166208/unknown.png
- https://cdn.discordapp.com/attachments/433289132710690819/433289321378873347/unknown.png

**Comment by Janmm14** [comment]
So the problem seems to be that alternate names of players are incorrectly completed.
