### ISSUE TITLE
AutoAutoRegister annotation / ignoreListener Methode

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#222]
Einen @AutoRegister oder ein pluginManager.ignoreListener( Listener listener ); hinzufügen um das registrieren von Listenern zu erleichtern.

------------------------------------------------------

@AutoRegister - Klassen Annotation
Bsp:
```
@AutoRegister
public class PlayerListener implements Listener {
    ....
}
```

Falls der Listener einen bestimmten Constructor hat muss man den Listener selbstständig mit pluginManager.registerListener( Listener listener ); registrieren und @AutoRegister weglassen.

------------------------------------------------------

pluginManager.ignoreListener( Listener listener ); - Methode im PluginManager (kann auch im Plugin drinne sein.)
Bsp:
```
onInstall() {
    getPluginManager().ignoreListener( new PlayerListener() );
}
```

**Comment by Gerrygames** [comment]
Bei der zweiten Option wäre eine ``@DontRegister`` Klassen Annotation deutlich besser ^^
Dann könnten alle Listener standardmäßig automatisch registriert werden, falls sie einen leeren Konstruktor besitzen. Falls sie keinen leeren Konstruktor haben oder mit ``@DontRegister`` annotiert sind, werden sie logischerweise nicht registriert.

Das halte ich außerdem für die bessere Option, da es (meiner Meinung nach) öfter vorkommt, dass man einen Listener bedingungslos beim Start registriert, als dass man einen Listener nur unter bestimmten Bedingungen registriert oder ihn während der Laufzeit registriert/"abmeldet".

Bei deiner zweiten Option müsste die Methode dann außerdem eher so aussehen:
``PluginManager#ignoreListener(Class<? extends Listener> listener)``

**Comment by Soupertonic** [comment]
Please write in English. We can't process non-English issues. If you still deem this relevant and you'd like to make the same proposal, please open an additional issue for that.
