### ISSUE TITLE
Item does not match

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#225]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Das man Touch Dirt etc abbauen kann sowie sich mit Items in der Hand Damage zufügen kann

## Current Behavior

Kein Damage wenn man Item in der Hand hält und paar Blöcke kann man net abbauen

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

[latest.txt](https://github.com/GoMint/GoMint/files/1977885/latest.txt)

**Comment by geNAZt** [comment]
Error in custom ProxProx
