### ISSUE TITLE
Plugins don't have access to AdventureSettings of EntityPlayer

### ISSUE THREAD

**Issue by rdstonech** [gomint/gomint#229]
I can't get AdventureSettings from EntityPlayer, because this getter doesn't exists in gomint-api

## Expected Behavior
player.getAdventureSettings()...

## Current Behavior
player.getAdventureSettings()… ERROR

## Possible Solution
Add getter to EntityPlayer and add AdventureSettings class in gomint-api

## Steps to Reproduce (for bugs)
1. Make some plugin
2. Get player from anything
3. Try to get AdventureSettings

## Your Environment

* Version used: https://github.com/GoMint/GoMint/commit/167006cbd77912f455e8d72d7f4eb4986f4fc482
* Client version and OS: 1.2.13, Windows 10
* Operating System and version / java version of the server: Windows 10 x64 / java8-172
![image](https://user-images.githubusercontent.com/31804440/40013077-3a67261e-57b5-11e8-81b6-14e69483505a.png)

**Comment by geNAZt** [comment]
What do you want to change with adventure settings? Those are only flags for internal use directly with the MC:PE client and will likely never opened to the API. When you need something like no clip i can create API for that.

**Comment by rdstonech** [comment]
You can, but I ran into such a problem, that in adventure gamemode player can break blocks. I wanted to disable it manually through AdventureSettings

**Comment by geNAZt** [comment]
That sounds like a bug, nothing which should be done by a plugin developer. Will look into
