### ISSUE TITLE
Can't break BlockCobbleStone

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#230]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Cobblestone abbauen können

## Current Behavior

Man kann kein Cobblestone abbauen weder mit der Hand noch mit der Pickacxe

## Steps to Reproduce (for bugs)

1. Cobblestone abbuen
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by geNAZt** [comment]
Logs?

**Comment by LucGamesYT** [comment]
Stone:
09:56:17.000 [main] WARN  io.gomint.server.network.handler.PacketInventoryTransactionHandler - LucGamesYT broke block too fast: break time: 350; should: 7500 for Stone with ItemDiamondPickaxe
09:56:47.972 [main] WARN  io.gomint.server.network.handler.PacketInventoryTransactionHandler - LucGamesYT broke block too fast: break time: 300; should: 7500 for Stone with ItemDiamondPickaxe

**Comment by LucGamesYT** [comment]
MossyCobblestone :
09:57:15.290 [main] WARN  io.gomint.server.network.handler.PacketInventoryTransactionHandler - LucGamesYT broke block too fast: break time: 400; should: 2999 for MossyCobblestone with ItemDiamondPickaxe

**Comment by LucGamesYT** [comment]
IronOre
09:57:56.925 [main] WARN  io.gomint.server.network.handler.PacketInventoryTransactionHandler - LucGamesYT broke block too fast: break time: 651; should: 4500 for IronOre with ItemDiamondPickaxe

**Comment by LucGamesYT** [comment]
Und jede menge mehr
