### ISSUE TITLE
player.attack does not work

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#232]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Man sollte schaden bekommen

## Current Behavior

Man bekommt kein schaden
## Steps to Reproduce (for bugs)

1. player.attack aufrufen
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by geNAZt** [comment]
@EventHandler
    public void onBlockBreak( BlockBreakEvent event ) {
        event.getPlayer().attack( 2f, EntityDamageEvent.DamageSource.ENTITY_ATTACK );
    }

works for me. please add example code
