### ISSUE TITLE
is there no setBlock()?

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#239]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

setBlock() have been in all software i used, how come none for this?
## Your Environment

* Version used: Latest http://ci.gomint.io/job/GoMint/job/genazt/11/artifact/gomint-server/target/GoMint.jar
* Client version and OS: Windows 10
* Operating System and version / java version of the server: Java8
* Link to the logs: no logs

**Comment by EinBexiii** [comment]
https://github.com/GoMint/GoMint/blob/genazt/gomint-api/src/main/java/io/gomint/world/block/Block.java#L72

**Comment by XDqrkneZ** [comment]
that seems like changing the block type, is there no set?

**Comment by EinBexiii** [comment]
Yes, but air is also a block.

**Comment by XDqrkneZ** [comment]
`world.getBlockAt(x,y,z).setType(BlockBedrock.class);
`?

**Comment by EinBexiii** [comment]
yes
