### ISSUE TITLE
broke the block too fast 

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#244]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. I got error:` xLevie broke block too fast: break time: 606; should: 4500 for DiamondOre with ItemDiamondPickaxe` When I broke DiamondOre
2. Same for Emerald ore 10:35:40.849 [main] WARN  `io.gomint.server.network.handler.PacketInventoryTransactionHandler - xLevie broke block too fast: break time: 662; should: 4500 for EmeraldOre with ItemDiamondPickaxe`
3.
4.

## Your Environment

* Version used: latest artifact
* Client version and OS: windows10
* Operating System and version / java version of the server: windows10 java 8
* Link to the logs:

**Comment by Janmm14** [comment]
And emeraldore?
