### ISSUE TITLE
Wrong blocks dropping

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#254]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Diamond Ores should drop diamonds when you break them - this goes for all other ores such as emerald ore -> emerald, Coal ore - > coal

## Current Behavior

Break a diamond ore and it will give you diamond ore again
Break a emerald ore and it will give you emerald  ore again
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: http://ci.gomint.io/job/GoMint/job/genazt/11/artifact/gomint-server/target/GoMint.jar
* Client version and OS: Windows 10
* Operating System and version / java version of the server: Java 8 Windows 10
* Link to the logs:

**Comment by ghost** [comment]
Resolved by a commit made by @Janmm14 - f75bcc2c588be624e653402951974c6b7f596b48
Thank you for creating an issue.
