### ISSUE TITLE
Enderchests are broken

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#267]
Place an enderchest.
Put some items in the player hotbar
Start spam clicking on the enderchest.
If the inventory opens, press ESC and continue spamming
Your items will disappear

**Comment by geNAZt** [comment]
Can't reproduce

**Comment by Soupertonic** [comment]
This issue was deemed invalid because of not being reproducible. If you'd like to create an additional issue that covers the same problem/bug, please do so.
