### ISSUE TITLE
can't add doubles on new Location(world, x y z)

### ISSUE THREAD

**Issue by enricoangelon** [gomint/gomint#279]
new Location(); accepts only floats and can't add doubles if i don't use (float)pos

**Comment by Janmm14** [comment]
So safe your positions as floats and not as doubles.

**Comment by enricoangelon** [comment]
Yes but this can't be a permanent fix i think

**Comment by geNAZt** [comment]
Minecraft itself uses floats for positions, double precision would be a waste of resources and thus is not used and will not be
