### ISSUE TITLE
can't add int on sendMessage()

### ISSUE THREAD

**Issue by enricoangelon** [gomint/gomint#280]
Can't add int on sendMessage(), i can only with sendMessage("" + int);

**Comment by Janmm14** [comment]
Intended. (Its java and not php; java has strong types.) Why would one ever want to send a single number as message to the client? No need to shortcut the integer sending, simply use that workaround or Integer.toString(int)

**Comment by geNAZt** [comment]
Works as intended

**Comment by enricoangelon** [comment]
I make those issues to make api more easier, not to make people rage, i said this because like nukkit doesn't have those problems

**Comment by geNAZt** [comment]
API is easy enough, sendMessage expects a string, adding a override for int won't make any sense and would lead to aweful API design
