### ISSUE TITLE
After the update, EntityHuman name is bugged

### ISSUE THREAD

**Issue by enricoangelon** [gomint/gomint#281]
i'm using last build on jekins.
![screenshot 485](https://user-images.githubusercontent.com/34418030/42581253-9e779d7e-852c-11e8-93c9-216be938ce37.png)
Name of npc should be test:
        EntityHuman human = EntityHuman.create();
//skin is defined by variable.. location too
        human.setSkin(skin);
        human.setDisplayName("test");
        human.setNameTag("test");
        human.setNameTagVisible(true);
        human.setNameTagAlwaysVisible(true);
        human.spawn(location);

**Comment by geNAZt** [comment]
The nametag in 1.5.0.14 works different in the client. It uses the player name (which always is NPC: uuid in Gomints Case. 

I have not found a way to get the changing working for player entities and i doubt it will work in the future (they built extra code into the client to always show the nametag and the nametag is always the user name from the spawn packet). So the only solution i can think of is respawning the player when the name changes...
