### ISSUE TITLE
Combine item entities on close distance to prevent client and server lag

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#287]

**Comment by geNAZt** [comment]
This will be part of a additional system which i currently have not decided to build yet since it could be done with the API. Will decide later

**Comment by yodamweeb** [comment]
like this? https://github.com/jasonwynn10/VanillaEntityAI/blob/master/src/jasonwynn10/VanillaEntityAI/entity/neutral/Item.php#L32L40

**Comment by Janmm14** [comment]
@yodamweeb You probably wanted to mark lines 15-25 and not 32-40? The file doesn't even have 40 lines.

**Comment by yodamweeb** [comment]
yeah @Janmm14. But I tested that pm plugin and it don't work, just throws errors

**Comment by Soupertonic** [comment]
This issue was deemed obsolete. If you'd like to create an additional issue that covers the same problem/bug, please go ahead and do so.

> geNAZt: _can be done with API_
