### ISSUE TITLE
Please add EntitySnowball

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#294]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by Kaooot** [comment]
Why you are creating an Issue, when the EntitySnowball still not exists?

**Comment by LucGamesYT** [comment]
Gibt es nicht

**Comment by LucGamesYT** [comment]
https://github.com/GoMint/GoMint/tree/master/gomint-api/src/main/java/io/gomint/entity/projectile
