### ISSUE TITLE
World is null? And blocks are not correctly 

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#311]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:
Log:
[latest.log](https://github.com/GoMint/GoMint/files/2257636/latest.log)
Plugin:
https://github.com/TheAmyChan98/EnderGames
Schematic:
https://github.com/TheAmyChan98/SchematicSystem
YOUTUBE:
https://youtu.be/KnpFHk2oYpU?t=10s

**Comment by geNAZt** [comment]
Fixed with https://github.com/GoMint/GoMint/commit/782d74cb9a3cb02186e1a780508843838192ab5d
