### ISSUE TITLE
getKnockback() is missing in the EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#323]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by lukeeey** [comment]
So much for the issue template

**Comment by geNAZt** [comment]
Knockback will be calculated after the damage has been dealt. So there is no way to include getKnockback() in this event
