### ISSUE TITLE
Man kann kein anderen WorldGenerator benutzen egal was man macht man bekommt den Normal Generator

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#325]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by geNAZt** [comment]
Can't reproduce
