### ISSUE TITLE
Block.setBlockId Methode falscher Parameter

### ISSUE THREAD

**Issue by Foorcee** [gomint/gomint#327]
In der Block Klasse ist der Parameter von der setBlockId Methode falsch.
Es ist ein byte, aber es gibt BlockIds die größer als 128 sind.
Es sollte ein Integer sein

**Comment by Janmm14** [comment]
Die API hat keine setBlockId Methode.

**Comment by Foorcee** [comment]
Aber der Server

**Comment by geNAZt** [comment]
Der Server ist keine API, dennoch war die Methode falsch
