### ISSUE TITLE
Shading other plugin jars or gomint-server registers commands

### ISSUE THREAD

**Issue by lukeeey** [gomint/gomint#328]
We cant depend on other plugin jars or gomint-server in our plugins because it will re-register the commands and if the version in our plugin is different to the one on the server, commands will be overridden and unexpected behaviour may occur.

**Comment by geNAZt** [comment]
Don't shade them, problem solved

**Comment by Janmm14** [comment]
Or don't use annotations for the command system.

**Comment by lukeeey** [comment]
@Janmm14 How do i do that? And how dont i shade the dependencies i dont know how else to do it. I need access to `setBlockid` and `setBlockData` in gomint-server and apparently they wont be added to the api which is annoying @geNAZt

**Comment by Janmm14** [comment]
@lukeeey
Shading dependencies for example via maven is opt-in with maven-shade-plugin remove it from the pom for not shading or specify what to shade with scopes of dependencies: `<scope>provided</scope>` inside a `<dependency>` section will cause maven-shade-plugin to not shade by default.

More configuration options can be seen here: https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html

You can take a look at my plugin OpMint how to not use annotations for commands.

One should never shade in a plugin if the plugins should coexist on a server.

Why do you think that you are unable to use gomint-server if you do not shade it?

**Comment by lukeeey** [comment]
Ive always shaded stuff so i didnt know of any other way
