### ISSUE TITLE
Items dont craft when crafted the other way around 

### ISSUE THREAD

**Issue by DelxHQ** [gomint/gomint#329]
## Expected Behavior
Craft the item the player wants no matter what way they put items in the crafting table

## Current Behavior
When you craft an item a different way in the crafting table, the item seems to disapear but still takes the resources from the player.

## Steps to Reproduce (for bugs)

1. Get wood
2. Make a crafting table
3. Make sticks
4. Make a wooden axe the other way around

## Your Environment

* Version used:
* Client version and OS: Windows 10 Edition 1.5.3
* Operating System and version / java version of the server: Ubuntu 18.10 latest Java version
* Link to the logs:

**Comment by geNAZt** [comment]
Whats the other way around which works in vanilla

**Comment by DelxHQ** [comment]
Put the wood on the right instead of left when crafting an axe
