### ISSUE TITLE
is GoMint the future

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#335]
is it

**Comment by lukeeey** [comment]
What kind of question is that

**Comment by ghost** [comment]
is GoMint the future

**Comment by DelxHQ** [comment]
Explain a bit more.

**Comment by Janmm14** [comment]
maybe

**Comment by ghost** [comment]
is gomint gonna be the most used mcpe software in the future

**Comment by DelxHQ** [comment]
Probably not, but who knows
