### ISSUE TITLE
how to add scoreboard

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#336]
how can i add scoreboard with the first scoreboard api

**Comment by Janmm14** [comment]
Gomint.createScoreboard()
Then use Scoreboard's functions to set the stuff.
Then use EntityPlayer.setScoreboard

**Comment by ghost** [comment]
so it is implemented to mcpe?

**Comment by DelxHQ** [comment]
Only in 1.7

**Comment by geNAZt** [comment]
In the latest beta yes
