### ISSUE TITLE
Click on ItemFireworkCharge brings the client to crash

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#350]
## Current Behavior

I add the item to a fake inventory and if I click on the item my client crashes

## Expected Behavior

I expect that my client doesn't crash when I add the item to a fake inventory.

## Steps to Reproduce (for bugs)

1. Create a fake (unbound) inventory
2. Add the item to the inventory via. `ItemFireworkCharge.create(1).setData((short) 2);`
3. Open theiInventory
4. Click on it

## Your Environment

* Version used: newest
* Client version and OS: 1.6.1 & windows10
* Operating System and version / java version of the server: win10, java8
* Link to the logs: there is no error in the logs

**Comment by Soupertonic** [comment]
This issue was deemed invalid. If you'd like to create an additional issue that covers the same problem/bug, please go ahead and do so.
