### ISSUE TITLE
Liquids should flow

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#354]
## Expected Behavior

Liquids are expected to have flow behaviours.

## Current Behavior

Liquids dont flow if you place them. The stay just as a (transparent) block.

**Comment by Janmm14** [comment]
expected behaviour equals current behaviour xd

**Comment by ghost** [comment]
>           expected behaviour equals current behaviour xd

Changed.

**Comment by Soupertonic** [comment]
This issue got resolved by several commits a few days ago. 

051c18082f70b689b3bf562e562de61ec662620a,
05dcb7891ad6d8965be8c95a42cf0177d31c46b4, 
dd6c756a35b558ea743863458cfece2daa0c3634
