### ISSUE TITLE
Chunks dont display correctly

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#358]
## Expected Behavior

If you join on a server you should see all chunks around you, but here its not the case,

## Current Behavior

Chunks dont display for the Client.
![Issue Pic](https://user-images.githubusercontent.com/25907843/46432566-db92af00-c74e-11e8-80b5-1065a9ce484b.png)

## Steps to Reproduce (for bugs)

1. Join on the server
2. Fly around
3. Sometime 1-2 minutes later comes this issue

## Your Environment

* Version used: newest GoMint build from jenkins (http://ci.gomint.io/job/GoMint/job/master/113/artifact/gomint-server/target/GoMint.jar)
* Client version and OS: 1.6 and win10

**Comment by lukeeey** [comment]
What world type is it?

**Comment by ghost** [comment]
Could you please check if the issue is still relevant? Changes have been made to the chunk generator. The issue might have been solved by those commits.

**Comment by Soupertonic** [comment]
Related to #537. Because of #537 being not that old, this issue will be closed in favor of it.
