### ISSUE TITLE
API design - Singleton and plugin instance inside command handlers

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#367]
## Current Behavior
Plugin creators use static plugin singleton getters in their command handlers. The alternative would be to not use the annotation framework for commands, but something similar to this which doesn'T look nearly as good: https://github.com/Janmm14/OpMint/blob/master/src/main/java/de/janmm14/opmint/commands/OpCommand.java#L17-L25

## Possible Solution

Automatically fill in a field in the Command class containing the plugin object and provide a getter. Maybe use generics and unsafe casting in the getter to prevent casting in the command.

**Comment by geNAZt** [comment]
There already is a @InjectPlugin annotation doing that

**Comment by geNAZt** [comment]
https://github.com/GoMint/GoMint/blob/master/gomint-server/src/main/java/io/gomint/server/plugin/SimplePluginManager.java#L281

**Comment by Janmm14** [comment]
oh rip
