### ISSUE TITLE
Scoreboards 1.7

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#378]
hi, 1.7 is out and scoreboard was tested in this version when it was on beta right

**Comment by KCodeYT** [comment]
GoMint works with the 1.7 and scoreboards work too

**Comment by XDqrkneZ** [comment]
@EventHandler(priority = EventPriority.LOWEST)
	public void onJoin(PlayerJoinEvent event) {
		EntityPlayer player = event.getPlayer();
		Scoreboard s  = new Scoreboard() {
			@Override
			public ScoreboardDisplay addDisplay(DisplaySlot displaySlot, String s, String s1) {
				this.addDisplay(DisplaySlot.SIDEBAR, "test","test1");
				return null;
			}
			@Override
			public void removeDisplay(DisplaySlot displaySlot) {
			}
		};
		player.setScoreboard(s);
	}

**Comment by KCodeYT** [comment]
Why The Fuck are you using new Scoreboard()?

**Comment by XDqrkneZ** [comment]
what then

**Comment by KCodeYT** [comment]
There is a GoMint.instance().createScoreboard(); Method please use them instead of new Scoreboard();

**Comment by XDqrkneZ** [comment]
and then?

**Comment by XDqrkneZ** [comment]
nvm

**Comment by ghost** [comment]
Is this issue resolved then?

**Comment by XDqrkneZ** [comment]
why is the line number beside the message

**Comment by KCodeYT** [comment]
we are not Microsoft Studios, please ask them. We have not developed the Scoreboard GoMint only sends the Packets for them.

**Comment by DelxHQ** [comment]
There always has been numbers on scoreboards @XDqrkneZ

**Comment by XDqrkneZ** [comment]
how do you add multiple lines? 
@EventHandler(priority = EventPriority.LOWEST)
	public void onJoin(PlayerJoinEvent event) {
		EntityPlayer player = event.getPlayer();
		Scoreboard s = GoMint.instance().createScoreboard();
		s.addDisplay(DisplaySlot.SIDEBAR,"-- "+player.getName()+" --","")
			.addLine("This is line one",1);
		player.setScoreboard(s);
	}

**Comment by XDqrkneZ** [comment]
I know @DelxHQ but the number is right beside the message. Isn't it supposed to stay in the corner

**Comment by KCodeYT** [comment]
@XDqrkneZ please close this issue and ask questions in the GoMint Discord (https://discord.gg/qC4nJVN) in #api-questions
