### ISSUE TITLE
What are some perks of using this software over PocketMine?

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#382]

**Comment by lukeeey** [comment]
PocketMine is in PHP and therefore is slower. GoMint also has a nice API and is future proof as it is built from the ground up with new features and isn't just hacky code or missing core features like PocketMine.

**Comment by XDqrkneZ** [comment]
What makes you say PHP is slow

**Comment by dktapps** [comment]
probably the fact that it's slow?

**Comment by geNAZt** [comment]
Typehinting seems slow, Memory management is garbage.

The only valid upside that PHP has is that it boots fast and doesn't need a compiler.

**Comment by SOF3** [comment]
If your server only runs for a few hours, maybe you gain more time in PHP because code-writing time is greatly reduced and compensates the CPU time affected by performance.

**Comment by lukeeey** [comment]
Ay the squad is here

**Comment by yodamweeb** [comment]
@dktapps what made you continue PocketMine after it died after knowing that PHP is slow?

**Comment by dktapps** [comment]
this isn't a PM discussion forum, I won't discuss this here.
