### ISSUE TITLE
I realized that when I leave the server and join back, my items are gone

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#385]
I realized that when I leave the server and join back, my items are gone

**Comment by KCodeYT** [comment]
Player Data isnt implementet in to GoMint

**Comment by ghost** [comment]
i figured. so is getting an item's id?

**Comment by KCodeYT** [comment]
From what u mean?

**Comment by ghost** [comment]
`@Override
    public CommandOutput execute(CommandSender commandSender, String s, Map<String, Object> map) {
        CommandOutput output = new CommandOutput();
        EntityPlayer player = (EntityPlayer) commandSender;
        ItemStack itemHand = player.getInventory().getItemInHand();
        player.getInventory().getItemInHand().
        return output.success(ChatColor.YELLOW + "The ID for "+itemHand.getType() + " is " +itemHand.getId or something.());
    }`

**Comment by KCodeYT** [comment]
no because there are no item ids in the minecraft bedrock edition

**Comment by ghost** [comment]
yes there is

**Comment by ghost** [comment]
https://github.com/pmmp/PocketMine-MP/blob/a49abff099723f213f77416537ec70c3438e8a56/src/pocketmine/item/Item.php#L662

**Comment by KCodeYT** [comment]
Is PocketMine from Microsoft?

**Comment by ghost** [comment]
did pocketmine make its own item ids then?

**Comment by KCodeYT** [comment]
yes

**Comment by KCodeYT** [comment]
so i think it

**Comment by KCodeYT** [comment]
Ouh the item have ids but i dont think geNAZt would suggest that players use them

**Comment by lukeeey** [comment]
There once was item ids in the game. PocketMine was created a long time ago when they were still a thing.

GoMint, on the other hand, was. created more recently in comparison.

I know there is still some sort of "runtime ids" but I'm not quite sure what they are. Minecraft has primarily moved to string ids though (e.g. Air: old id: 0, new id: minecraft:air)

**Comment by geNAZt** [comment]
Guys this is a issue tracker not a chat. Discord is linked in the readme.

**Comment by ghost** [comment]
will players data be added soon or later

**Comment by ghost** [comment]
Is this a question or statement?

**Comment by ghost** [comment]
question

**Comment by ghost** [comment]
Is going to be added probably soon. We're actually just figuring out how to save the player data. Either NBT or a custom storage format. It is quite hard because geNAZt doesn't target full compatibility, that's at least what I've read in the Discord chat.
