### ISSUE TITLE
GoMint is unable to run on/in Java 11 environment

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#390]
**Describe the bug**
GoMint almost instantly crashes when using Java 11. Instantly crashing meaning GoMint doesn't get further than scanning for plugins and worlds. GoMint just stops and doesn't print out any crash reports, logs or anything near that.

**To Reproduce**
Welp, just install JDK/JRE 10 and add it to the environment path.

**Expected behavior**
Expected behavior would be GoMint running just fine without any flaws and to not decide between JDK and or JRE 8 / 11.

**Screenshots**
JDK 8: https://i.imgur.com/yC2ra14.png
JDK 11: https://i.imgur.com/chuz2IY.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version Build 1809 (Latest major redstone update)

**Additional context**
Why bother adding support for Java 11? Well, because Java 11and beyond evolves way faster than most 
people can think of. Java 11and upcoming versions are introducing a lot of new features which obviously people want to try out and maybe at the end develop GoMint plugins using the named JDK versions. Developers should not stand between two JDK versions and decide whether to use GoMint for their choice of server software or not.

**Comment by geNAZt** [comment]
JDK 10 is EOL so no support given

**Comment by ghost** [comment]
The whole issue was/is actually about Java 11, not 10. My bad. I had Java 11 installed, not 10. Java 11 is going to be LTS.

**Comment by geNAZt** [comment]
Java 11 crashes with 0xC00000F1 as error code which is a NT error. So the VM seems to crash itself without any signs on why, not even a crashlog is created. Never seen that before and i don't know what i should do

**Comment by lukeeey** [comment]
What is all this LTS shit? Java 7 and 8 surely couldn't have both been LTS yet they were widely supported on many things

**Comment by geNAZt** [comment]
7 and 8 are LTS 

See:
https://i.imgur.com/DsDC3Zl.png

https://www.oracle.com/technetwork/java/javase/eol-135779.html

**Comment by ghost** [comment]
Might have been fixed.
