### ISSUE TITLE
Latest Jenkins build is 1.6

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#391]
Check it out its 1.6 the latest jebkins build

**Comment by KCodeYT** [comment]
close issue here is the latest build: http://ci.gomint.io/job/GoMint/job/master/lastSuccessfulBuild/artifact/gomint-server/target/GoMint.jar

**Comment by KCodeYT** [comment]
and its 1.7

**Comment by lukeeey** [comment]
@KCodeYT Are you sure the latest build supports 1.6?

**Comment by KCodeYT** [comment]
No it only supports the 1.7 why should it also support the 1.6?

**Comment by lukeeey** [comment]
Oh i read the question wrong sorry
