### ISSUE TITLE
Add to be able to reverse scoreboard numbers like JE

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#392]
**Is your feature request related to a problem? Please describe.**
With the current Scoreboard added to gomint, the numbers always starts from 1 and cant start from 15 like JE
 Here is a video of what I meant, the scoreboard has 15 at the top and 1 at the bottom https://www.youtube.com/watch?v=LHWiKUruEww

while with gomint that 1 is always at the top and cant be at the bottom

so add something to be able to reverse numbers or something

**Comment by Janmm14** [comment]
#384
