### ISSUE TITLE
Add query system

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#396]
I want my server to be publicized through websites like https://minecraftpocket-servers.com/ but i cant cuz they cannot query the server(see if the server is online, see player count etc) so it would be nice if you add querying

**Comment by lukeeey** [comment]
I believe a PR will be opened for this shortly.

**Comment by ghost** [comment]
Any updates

**Comment by lukeeey** [comment]
@Shad0wCore

**Comment by DelxHQ** [comment]
Please.

**Comment by ghost** [comment]
Takes time.

**Comment by lukeeey** [comment]
Not really but alright

**Comment by ghost** [comment]
@lukeeey Go ahead. Nobody's hindering you from implementing it yourself.
