### ISSUE TITLE
Wrong rotations of some blocks

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#403]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Janmm14** [comment]
"some blocks" i see really good issue description. what blocks? all rotateable? which blocks with rotation are not affected?

When does the issue occurr? on world load? on place? always?

**Comment by geNAZt** [comment]
#402
