### ISSUE TITLE
Neat console

### ISSUE THREAD

**Issue by XDqrkneZ** [gomint/gomint#405]
Can u make gomint console so that it dont say main.io.whatever and maybe add colors

**Comment by lukeeey** [comment]
That would be nice. Maybe only enable the FQN if a debug command line option is present.

**Comment by geNAZt** [comment]
its a console and not a nice fancy ui. its there to see errors and nothing more

**Comment by lukeeey** [comment]
When running a server it is useful to be able to see certain things in console. Hydreon did a good job of this with [Katana](https://github.com/hydreon/katana) by removing all the bullshit and having nice, colourful formatted text
