### ISSUE TITLE
World Converter crashes when it tries to convert signs

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#449]
If the world converter tries to convert the signs on my world it crashed.

1. Use my world: https://cdn.discordapp.com/attachments/383232557229015041/520628710357860352/lobby.zip
2. Download GoMint.jar: http://ci.gomint.io/job/GoMint/job/master/lastSuccessfulBuild/artifact/gomint-server/target/GoMint.jar
3. Start the server with the world as default world.

The sign dont get converted

https://imgur.com/a/D6WXqJt

 - OS: Microsoft's Windows
 - Version: 10

**Comment by geNAZt** [comment]
Converter is gone and will not come back
