### ISSUE TITLE
start up error

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#459]
https://pastebin.com/qAaGKekd

**Comment by ghost** [comment]
using latest build

**Comment by Janmm14** [comment]
A server is already running on that port.

**Comment by ghost** [comment]
no

**Comment by Janmm14** [comment]
Yes. Thats what the error says.
And there is no way the error is wrong.

**Comment by lukeeey** [comment]
This can happen when you close the terminal while the server is still running. Just a restart of your computer or killing the java process will most likely fix it.

**Comment by ghost** [comment]
Did you even try the latest build

**Comment by lukeeey** [comment]
You didnt fill out the issue template so i could not know you were using the latest build. I have also not confirmed that this is an issue, so until someone does or you can provide extra information then this issue will remain closed.

**Comment by DelxHQ** [comment]
@captainleviftw Latest build is working fine for me. This is obviously an issue on your end.
