### ISSUE TITLE
make blocks look smoother after breaking them

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#460]
when u break blocks, it looks like its shaking but that doesn't happen in vanilla.

**Comment by DelxHQ** [comment]
Shaking?

**Comment by ghost** [comment]
shaky

**Comment by DelxHQ** [comment]
I don't think I have that issue.

**Comment by dktapps** [comment]
It does happen in vanilla, it's just random. It also happens on other custom servers. It's a bug in the client.

**Comment by ghost** [comment]
it dont happen in vanilla for me.

**Comment by Janmm14** [comment]
Doesn't look like its a server bug for me.

**Comment by DelxHQ** [comment]
@captainleviftw Is right, I dont think this is a client bug. When you break the block, the entity feels laggy as it drops.

**Comment by dktapps** [comment]
It has to do with rendering. Sometimes frames replay on the client side which makes it look stuttery. This is something you can see on any server and also vanilla when under load.
