### ISSUE TITLE
Create separate repository for API?

### ISSUE THREAD

**Issue by volcanopowder** [gomint/gomint#464]
I am viewing the source and issue list for this project, and I noticed that the API and the server source, not to mention all of the other components, are all stored in the same repository. 

For better cross-referencing and easier handling of the build-system, wouldn't it be better to separate them into different repositories?

This is just a consideration, but not only would the build-system be faster, but it would also be more divided and contained. For instance, a change to the API would only require that build to be updated instead of the entire project.

Maybe not, but perhaps it's worth considering. Right now there is such a large overhead that it makes it a bit difficult to document or make implementations without a library built.

Cheers!

**Comment by ghost** [comment]
I suggest not

**Comment by lukeeey** [comment]
You can build individual modules. The api should stay in this repo or it would be a nightmare to implement new features.

I do however agree that some of the other modules should have seperate repos. Maybe gomint-native could stay here though.

**Comment by ghost** [comment]
Oof. I'd say you've got a point there. I don't like this bloated GoMint server repository too. However, it makes development on GoMint so much more "efficient". Efficiency in terms of not maintaining all the separate repositories, maintaining updates etc. 

As I already said, I kinda agree with you on this but for the sake of development and "efficiency" I think GoMint's not being split up into several repositories until GoMint is stable and hits its first release date.

**Comment by ghost** [comment]
Added it to the first release milestone. As for now, there's not going to happen a lot so I'mma lock the conversation. Thank you for giving us feedback.

**Comment by lukeeey** [comment]
As long as you leave the api here
