### ISSUE TITLE
Take actions on updating to MC:PE 1.8 client and features

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#465]
1.8 released might as well update

**Comment by ghost** [comment]
Can you clarify a bit more what you mean?

**Comment by Janmm14** [comment]
Uhm support for the MC:BE 1.8 Client and Features?

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/32599317/50038286-bd64ed00-ffe2-11e8-974f-0e537c6ef8dc.PNG)

**Comment by ghost** [comment]
updating gomint to be compatible with the latest mcpe version is priority medium?

**Comment by ghost** [comment]
Imho it is. Upgrading is always easier than downgrading. It just prevents a bloated TODO list and less stuff is easier to keep track of. In general, GoMint still lacks a lot of vanilla features and they are priority number one.

**Comment by ghost** [comment]
As for an example, the Glowstone server project still lacks a lot of vanilla features of Minecraft Java Edition. Reasoning behind this is, at least partially, that they're trying to implement each and every single update of vanilla Minecraft Java Edition. Mob entity AI still missing, I guess environmental lighting missing too and a lot of more stuff. That's the reason why the priority is "just" _medium_. Heck, it could even be set to _low_.

**Comment by ghost** [comment]
ok
