### ISSUE TITLE
BirchTree#grow() call grows an oak tree

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#471]
Birch is the white log.. but it grows oak logs.
Here's the code I executed:
```java
BirchTree birchTree = new BirchTree();
birchTree.grow( GoMint.instance().getWorld( world ), 7, 5, 7, fastRandom );
```
> EDIT: Fixed the incorrect formatted code block ~Shad0wCore

**Comment by ghost** [comment]
Can anybody confirm this? Maybe by posting a video or a short clip, gif, whatever? Can't test it.

**Comment by Janmm14** [comment]
(code shows it sets birch type)

**Comment by ghost** [comment]
But I'd like to see it happening in the actual game

**Comment by ghost** [comment]
https://youtu.be/M2YYpg8LqLY

**Comment by geNAZt** [comment]
Fixed
