### ISSUE TITLE
`java.lang.Exception: null` when programmatically setting a player's gamemode

### ISSUE THREAD

**Issue by bwdotdev** [gomint/gomint#479]
**Describe the bug**
When setting a player's gamemode an exception is thrown and the player's gamemode is not changed.

**To Reproduce**
```java
player.setGamemode(Gamemode.CREATIVE);
```

**Expected behavior**
No exception and a change of gamemode.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/10724949/50356576-6e6f0880-054a-11e9-8a75-e09e1ca30593.png)

**Additional context**
I have confirmed (with the help of `System.out.println()`) that both the player and the gamemode are valid.
I am using [build #35](http://ci.gomint.io/job/GoMint/job/master/35/).

**Comment by ghost** [comment]
Null pointers again. Great. I'm gonna investigate into this

**Comment by ghost** [comment]
When exactly is this exception being thrown? Can you provide me a full console log?

**Comment by bwdotdev** [comment]
![image](https://user-images.githubusercontent.com/10724949/50357303-6fee0000-054d-11e9-94d2-a79e35382ef0.png)

I'm not doing anything more than attempting to set the player's gamemode after receiving an event from a Socket.IO server.

**Comment by bwdotdev** [comment]
Entire log:
![image](https://user-images.githubusercontent.com/10724949/50357411-d5da8780-054d-11e9-88e7-bdf657d8d0ca.png)

**Comment by ghost** [comment]
So, basically what's happening is, is that the method is complaining about "you" trying to send a packet from another thread than the GoMint main thread. The following `if`-statement throws the exception:
https://github.com/GoMint/GoMint/blob/9e1e5d0e5a9d8ee879bdda03a89427b2c0e89e09/gomint-server/src/main/java/io/gomint/server/network/PlayerConnection.java#L283-L288
I think this check is in place to prevent data races happening between Netty and GoMint or packet serializations or whatever.

Where do you invoke the function to change the player's gamemode?

**Comment by bwdotdev** [comment]
Makes sense.

`player.setGamemode()` is being called here:
![image](https://user-images.githubusercontent.com/10724949/50357629-792b9c80-054e-11e9-9f69-cfecbe42274b.png)

PlayerActions.setGamemode() is being called within a Socket.IO listener, similar to this:
```java
socket.on("event", new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        // call PlayerActions.setGamemode
    }
});
```

**Comment by ghost** [comment]
Try this one. This should work. This invokes a runnable on the GoMint main thread and should set the player's game mode without an exception being thrown:
```java
socket.on("event", new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        UUID playerUUID = // ... ;
        PlayerActions playerActions = // ... ;
        Plugin plugin = // ... ; // Your plugin instance
 
        // One of those two I think is being executed on the main thread
        plugin.getScheduler().execute( ... )
        plugin.getScheduler().schedule( ... )
    }
});
```

**Comment by bwdotdev** [comment]
Awesome, `plugin.getScheduler().execute( ... )` worked a treat. Thanks.
