### ISSUE TITLE
Implement NBT Tags

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#482]
**Is your feature request related to a problem? Please describe
. I'm always frustrated when i need to do something that nbt tags will solve but i cant since it's not implemented yet

**Describe the solution you'd like**
Add nbt tags.

**Describe alternatives you've considered**
add nbt tags.

**Additional context**
.https://www.digminecraft.com/data_tags/index.php

**Comment by dktapps** [comment]
pls no

**Comment by geNAZt** [comment]
If there is no API for what you want to-do feature request it please. NBT will never be part of the API

**Comment by lukeeey** [comment]
nbt is vanilla though

**Comment by ghost** [comment]
If NBT is wished that much then create a plugin for it but do not implement it as default in the API.

**Comment by dktapps** [comment]
> nbt is vanilla though

That's exactly why it shouldn't be part of the API. NBT is just a storage format. Exposing it to the API means exposing Mojang internals to the API, which GoMint developers cannot shield plugin devs from when it breaks.
NBT shouldn't be part of the API any more than item magic IDs or packets.
