### ISSUE TITLE
Error while connecting with ProxProx

### ISSUE THREAD

**Issue by GWD1** [gomint/gomint#49]
`EntityPlayer has been disconnected whilst logging in: Skin i
s invalid or corrupted`

**Comment by geNAZt** [comment]
GoMint config?

**Comment by GWD1** [comment]
?

**Comment by geNAZt** [comment]
You need to run GoMint in onlyXbox false, and i think you don't have that setting in your server. Thus the error that the skin is invalid

**Comment by GWD1** [comment]
Ok
