### ISSUE TITLE
Startup warning

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#491]
**Describe the bug**
Open a GoMint server and you will see this warning
```java
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/C:/Users/qw/Desktop/gomint/GoMint.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
**To Reproduce**
1. Run a gomint server
2. Look at the console
4. See warning

**Expected behavior**
No warning
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10
**Smartphone (please complete the following information):**

**Additional context**

**Comment by geNAZt** [comment]
Javassist is gone now
