### ISSUE TITLE
Server doesn't know I am holding an Item

### ISSUE THREAD

**Issue by TwistedAsylumMC** [gomint/gomint#493]
**Describe the bug**
When I interact with an item, the server thinks I am not holding any item

**To Reproduce**
1. Run a plugin with the following code:
```java
    @EventHandler
    public void onInteract(PlayerInteractEvent event){
        EntityPlayer player = event.getPlayer();
        ItemStack item = player.getInventory().getItemInHand();
        player.sendMessage(Objects.toString(item));
    }
```
2. Look at the outcome

**Expected behavior**
Item would have correct data (count etc) when you interact

**Screenshots**
![image](https://user-images.githubusercontent.com/30378179/50615939-63b75a80-0ede-11e9-91db-4e79c66f35d6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] 1803

**Additional context**

**Comment by Soupertonic** [comment]
This issue was deemed invalid. If you'd like to create an additional issue that covers the same problem/bug, please go ahead and do so.
