### ISSUE TITLE
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#501]
**Describe the bug**

**To Reproduce**
Run GoMint.jar and see `WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.` 

**Expected behavior**
no such warning
**Screenshots**
```WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.```
**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
Wait a little bit after that..

**Comment by Janmm14** [comment]
Thats nothing to worry about I'd say, its a warning.

**Comment by geNAZt** [comment]
This is a warning from log4j2. Nothing i can do against and since it doesn't harm any functionality you can simply ignore it.
