### ISSUE TITLE
Repo.GoMint.io is down

### ISSUE THREAD

**Issue by TheRasPiGuy** [gomint/gomint#502]
So, I am trying to build GoMint on my Windows machine, but Maven fails at GoMint Server because repo.gomint.io is down. Any etc on when it will be back up?

**Comment by ghost** [comment]
No idea. @geNAZt did not respond ever since the repo went down. Total radio silence. No information or response whatsoever. Unfortunately, there are no fallback repositories.

**Comment by TheRasPiGuy** [comment]
Dangit. Do you know of any other server software? PMMP and NukkitX don't seem to be working for me.

**Comment by ghost** [comment]
Wrong issue section. 😅

**Comment by geNAZt** [comment]
Has been resolved by moving to maven central
