### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#504]
Update to 1.10 please?

**Comment by TobiasGrether** [comment]
I think you won't see any change in the next 20 years...

**Comment by ghost** [comment]
@TobiasG-DE Why? Is the developer imprisoned? :D

**Comment by ghost** [comment]
He's just pretty busy right now and doesn't find any time to work on GoMint.

**Comment by sshadowcore** [comment]
He's just pretty busy right now and doesn't find any time to work on GoMint.
