### ISSUE TITLE
Player Bounding Box Issue

### ISSUE THREAD

**Issue by andrei1058** [gomint/gomint#505]
**Describe the bug**
The player bounding box seems too big, 
I made a video about it:
https://www.youtube.com/watch?v=015mTOemlEk

**Desktop (please complete the following information):**
 - OS: win 10
 - Version: Microsoft Windows [Version 10.0.17763.475]

**Comment by enricoangelon** [comment]
Video not available. Not a valid issue as now.

**Comment by Soupertonic** [comment]
Deeming this as stale because of the op not responding or providing a new video.
