### ISSUE TITLE
Repo 404

### ISSUE THREAD

**Issue by Him188** [gomint/gomint#508]
I got 404 when visiting http://repo.gomint.io/content/groups/public/

**Comment by lukeeey** [comment]
This project is pretty much dead.

**Comment by geNAZt** [comment]
Its fixed. The nexus died. Sorry for the problems 😁

**Comment by lukeeey** [comment]
repo.gomint.io goes to namecheap (although gomint.io works) and the link the op specified is still a 404

**Comment by Schuwi** [comment]
The link works fine for me...

**Comment by andrei1058** [comment]
It works for me as well

mar., 6 aug. 2019, 19:10 Schuwi <notifications@github.com> a scris:

**Comment by lukeeey** [comment]
Ah was the DNS being slow to update it works now

**Comment by Him188** [comment]
Is Gomint still alive? @geNAZt
