### ISSUE TITLE
Ghosted(?)

### ISSUE THREAD

**Issue by rjworks** [gomint/gomint#510]

**Comment by TobiasGrether** [comment]
wdym?

**Comment by rjworks** [comment]
> wdym?

there has been no updates

**Comment by Janmm14** [comment]
Yes, genazt went away from a company operating a minecraft java server. He created this in his free time back then for possible later usage by that company for a bedrock server. Unfortunaly this project never made it to a real high quality production-grade server before he decided to leave. I guess he now has less time and not that many ambitions regarding minecraft anymore.

**Comment by geNAZt** [comment]
I'm not ghosted. This is also OSS so everyone could have updated it. It currently gets updated for 1.14 so stay tuned
