### ISSUE TITLE
Commands are not showing up

### ISSUE THREAD

**Issue by enricoangelon** [gomint/gomint#523]
**Describe the bug**
When writing a registered command, the completion is not working and the command itself is not even listed

**Expected behavior**
Command list shows up when writing "/", completion working.

**Additional context**
Commands are fixed by me to not crash the server, maybe i forgot some other updates / additions

**Comment by Soupertonic** [comment]
> When writing a registered command

To type down a command in-game, in the chat window? Is it that what you mean?

**Comment by enricoangelon** [comment]
> > When writing a registered command
> 
> To type down a command in-game, in the chat window? Is it that what you mean?

Yes

**Comment by geNAZt** [comment]
Current gomint server commands work. I see no issues with it currently
