### ISSUE TITLE
directionVector

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#54]
ich hätte getDirectionVector 3d gemacht and dann evtl. noch getPlaneDirectionVector für 2d
Und die Methoden sollten dann auch in die Location-Klasse kopiert werden

**Comment by geNAZt** [comment]
So move direction calculations to the vector instead of location? Sounds like a good idea

**Comment by Janmm14** [comment]
I'm speakign about https://github.com/GoMint/GoMint/commit/8897bd40af3592007f3b8f3e2332980402d35dc6
