### ISSUE TITLE
items do not stack like mc java

### ISSUE THREAD

**Issue by rjworks** [gomint/gomint#566]
**Describe the bug**
items do not stack like mc java when they fall to the ground
**To Reproduce**
1. go join gomint server
2. drop or break blocks
3. see them not stack like mcjava

**Expected behavior**
expected to see them stack like mc java
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]windows
 - Version [e.g. 22]10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Janmm14** [comment]
Do dropped items stack in bedrock singleplayer?

Don't use mc java as comparision.

**Comment by rjworks** [comment]
yes they don’t
