### ISSUE TITLE
Wrong stone

### ISSUE THREAD

**Issue by rjworks** [gomint/gomint#570]
**Describe the bug**
The stones under dirts are wrong. I think those are double stone slabs instead of actual stones.
**To Reproduce**
join gomint.io
mine a couple blocks down to reach stone
see double stone slabs

**Expected behavior**
actual stone underneath dirst
**Screenshots**
![Minecraft Screenshot 2020 09 09 - 11 53 06 09](https://user-images.githubusercontent.com/46464980/92635505-2f8b6400-f293-11ea-963d-e235c2d7b657.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]windows
 - Version [e.g. 22]10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 2klm** [comment]
don't you have any texture pack installed ?
Otherwise it's definitely double stone slabs

**Comment by rjworks** [comment]
i do not
