### ISSUE TITLE
Item bow does not work

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#589]
**Describe the bug**
When I want to use the bow, it does not shoot an arrow

**To Reproduce**
Use a bow and shoot

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: GoMint 1.0.0 (MC:PE 1.16.20) - s:2e904fd8

**Comment by waltster** [comment]
Pointing to #549 and #273. To my knowledge, bows are not implemented yet.
