### ISSUE TITLE
gomint built in /op and /deop command

### ISSUE THREAD

**Issue by rjworks** [gomint/gomint#593]
Can gomint have its own /op command which gives player all permissions and /deop to remove it all?
there is a plugin for this but having it in gomint would be nicer i think

**Comment by Janmm14** [comment]
I built the plugin because genazt did not want to have it inside gomint.

**Comment by lukeeey** [comment]
https://github.com/gomint/GoMint/blob/master/gomint-server/src/main/java/io/gomint/server/command/vanilla/OpCommand.java

i added this ages ago

**Comment by lukeeey** [comment]
My bad, my implementation does not save them to a file so OpMint still has more features for now.

**Comment by geNAZt** [comment]
OP status should be saved in player data, this issue is done, the commands are there
