### ISSUE TITLE
CallerDetectorUtil.getCallerPlugin() does not work properly

### ISSUE THREAD

**Issue by juliarn** [gomint/gomint#615]
**Describe the bug**
CallerDetectorUtil.getCallerPlugin() uses SecurityManager#getClassContext to retrieve all classes on the current stack trace, filtering for a class extending the GoMint Plugin class.
Doing this via the stack trace is not very safe, the plugin class will not be in the stack trace, when the method is called inside a scheduler task or an event handler.

**To Reproduce**
Execute CallerDetectorUtil.getCallerPlugin() for example in an event handler, it will return null.

**Expected behavior**
CallerDetectorUtil.getCallerPlugin() should return the correct plugin, not dependening on the current stack trace

**Comment by Janmm14** [comment]
The fix is to check the classloader of each class to find PluginClassloaders and grab the plugin from there.
