### ISSUE TITLE
Deploy javadoc and sources jars to maven repo too

### ISSUE THREAD

**Issue by juliarn** [gomint/gomint#635]
Working with the GoMint API and spotting bugs would be a lot easier if one would be able to see the sources and the javadoc documention directly in the IDE.
I would be pleased if you could deploy these jars to the repo too.

**Comment by Janmm14** [comment]
Until this happens you could add my javadoc url manually to your IDE: https://janmm14.de/static/gomint/

**Comment by geNAZt** [comment]
Done
