### ISSUE TITLE
Refactor GoMint API to use fluid interfaces exclusively 

### ISSUE THREAD

**Issue by Soupertonic** [gomint/gomint#688]
### Preamble
This issue addresses updating the GoMint API to newer and more modern standards. One of these standards are " Fluid Interfaces". We would like to change the GoMint API in a way that we not only banish "getters" and "setters" completely, but also make it more comfortable to work with the  GoMint API.

### Implications
Changing the GoMint API means breaking other APIs. We would like to point out that we have a two week deprecation clause in place that allows for adaptation without surprises. However, once the the two week deprecation clause has passed deprecated symbols and declarations, including but not limited to, methods, fields, etc.; will be completely removed.

### Fluid Interfaces for the following API areas:
- [x] World API **(efa360996e2ebffa507cdb6855a2b3b595474232, 2d5e0231a4d47d9910f9b3c6ad0ef50c1fb1251b)**
- [x] Blocks API **(c61ec1c10f870d9dd45710dcbb13abb53c7bd976)**
- [x] Item API (wip @geNAZt)
- [x] Entity API (wip @fyradir)
- [x] Enchantment API (**da18ced28e5219fff3e30474371b491f4020b8f2, 51da64be4dad5d57a79982f2e95ca880527d526b)**
- [x] Inventory API (wip @geNAZt)
- [x] Plugin API **(01d36752d6e89e3eb66a79f2a9ef3258f88e9237)**
- [x] Player API **(3d2ce67574c432c1fdffd101f86d5d42424a88ab)**
- [x] Permissions API **(3d2ce67574c432c1fdffd101f86d5d42424a88ab)**
- [x] Maths **(3d2ce67574c432c1fdffd101f86d5d42424a88ab)** 
- [x] Scoreboard API **(22387a1b88beb777f31131212870821b37275d56)**
- [x] Scheduler API **(a2aa84b225e1945eff046181abef8e00805d0c9d)** 
- [x] `GoMint.instance()` access interface **(d4dd746b4ed5bf400b8976ed044b5ec3026c10ce)**

**Please note that even if a certain API of GoMint is not listed doesn't exclude it from API changes and breakages.**
_Development for this issue is being completed in branch [`refactor/fluid-interfaces`](https://github.com/gomint/gomint/tree/refactor/fluid-interfaces)_

**Comment by Janmm14** [comment]
suggesting unpin
