### ISSUE TITLE
Using GSON as a plugin dependency doesn't load due to missing java.sql modules

### ISSUE THREAD

**Issue by geNAZt** [gomint/gomint#709]
When using gson in a plugin it doesn't load since gson requires java.sql which can't be loaded for some reason. We need to check why this is the case and check if the module layer config in the plugin manager is correct

**Comment by nnnnt21** [comment]
I was the one having this problem adding 
--add-modules java.sql
to your start server script will fix the issue but not sure if thats just a bandaid for the initial cause
