### ISSUE TITLE
[3a1815] GoMint: io.gomint.server.GoMintServer.internalShutdown, io.gomint.server.GoMintServer.startAfterRegistryInit, io.gom...

### ISSUE THREAD

**Issue by GoMinty** [gomint/gomint#733]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><b><a href="https://gomint.sp.backtrace.io/dashboard/gomint/project/GoMint/group/3a181520ddb5bd62b05acafed3d022c5332c77c6ec346f8c8fd24af851e7a7d9">New error: [GoMint]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>GoMint</td></tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>java.lang.RuntimeException</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
io.gomint.server.GoMintServer.internalShutdown
io.gomint.server.GoMintServer.startAfterRegistryInit
io.gomint.server.Bootstrap.bootstrap
io.gomint.server.Bootstrap.main</code>
        </td>
    </tr></table>

**Comment by geNAZt** [comment]
This was only for testing.
