### ISSUE TITLE
Can break blocks like glass / ice

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#74]
You can break blocks like glass and ice, although the blockbreak event ist cancelled. The block is for the player invisible, but for the other players not.

**Comment by Goodstuff4UonYT** [comment]
Flower Pot

**Comment by Goodstuff4UonYT** [comment]
wooden slabs

**Comment by Goodstuff4UonYT** [comment]
![image](https://user-images.githubusercontent.com/19636759/34468380-f118345a-ef07-11e7-9ae9-8d7f43c24a2e.png)
this block, too

**Comment by Janmm14** [comment]
basically all blocks i guess?!
