### ISSUE TITLE
Better and simple Linux Compatibility

### ISSUE THREAD

**Issue by MonoAdrian23** [gomint/gomint#740]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when. Heyho GoMint Team, our Software is really nice but for Quality Hosters No Argument for offer this Software.
Because, Linux Compatibility is very hard with depends.
Seems Like GoMint is only for Windows.
And this have's No future.
Please make GoMint simple for Linux Users.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geNAZt** [comment]
Its as simple as install openJDK 11, run start.sh. I don't see a problem in that. Its the exact same way as on windows.
