### ISSUE TITLE
Invisible Effect: You are invisible for other players, but not for yourself

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#79]
If you add an inivisible effect to yourself other players cant see you, but you can see yourself
![image](https://user-images.githubusercontent.com/19636759/34412144-b37ec0d4-ebdb-11e7-9a89-1999ce6c8d05.png)

`  p.addEffect(PotionEffect.INVISIBILITY, 1, 3, TimeUnit.DAYS);`

**Comment by ghost** [comment]
MultiLabs uses nukkit, what

**Comment by Goodstuff4UonYT** [comment]
yes?

**Comment by Goodstuff4UonYT** [comment]
still not working
